### ISSUE TITLE
upgrading to 4.1.0 and getting unable to check for version update

### ISSUE THREAD

**Issue by Saffa001** [sassoftware/SAS-lsm#2]
Hi

I have two Environments DEV and PROD and I have upgraded SAS-slm  in both environments. DEV environment has no issue but PROD environment i am getting this message:

<< WARNING >> SAS_lsm was unable to check for version updates. You are currently using version 4.1.0.
Please reference https://api.github.com/repos/sassoftware/sas-lsm/releases/latest to ensure you are using the newest version of SAS_lsm.

Thanks,

**Comment by ajforeman** [comment]
This is not an error that indicates a problem.

SAS-lsm attempts to query GitHub API to check latest release when the utility is run. If that query obtains an empty response, the message you are observing is displayed. Essentially this means that the queried URL was not available -- likely due to network restrictions.

You can review the code for this function here to better-understand the attempted URL call: https://github.com/sassoftware/SAS-lsm/blob/master/lsm_components/check_version.fn
